In [1]:
import pandas as pd
import numpy as np

In [2]:
stock = pd.read_csv('../data/processed/feature_data.csv')
cash_flow = pd.read_csv('../data/raw/aapl_cash_flow.csv')
aapl_dividends = pd.read_csv('../data/raw/aapl_dividends.csv')
aapl_historical_data = pd.read_csv('../data/raw/aapl_historical_data.csv')
aapl_income_statement = pd.read_csv('../data/raw/aapl_income_statement.csv')
aapl_institutional_ownership = pd.read_csv('../data/raw/aapl_institutional_ownership.csv')
aapl_master_dataset = pd.read_csv('../data/raw/aapl_master_dataset.csv')
aapl_quarterly_financials = pd.read_csv('../data/raw/aapl_quarterly_financials.csv')
aapl_technical_indicators = pd.read_csv('../data/raw/aapl_technical_indicators.csv')

In [3]:
data = [stock,cash_flow,aapl_dividends,aapl_historical_data,aapl_income_statement,aapl_institutional_ownership,aapl_master_dataset,
        aapl_quarterly_financials,aapl_technical_indicators
       ]

In [13]:
aapl_technical_indicators

,Unnamed: 0,Date,Open,High,Low,Close,Adj Close,Volume
0,0,2004-12-31,4.635000,4.642857,4.573571,4.600000,3.114000,69647200.0
1,1,2005-01-03,4.627143,4.650714,4.471428,4.520714,3.060327,172998000.0
2,2,2005-01-04,4.556428,4.676429,4.497857,4.567143,3.091757,274202600.0
3,3,2005-01-05,4.604286,4.660714,4.575000,4.607143,3.118836,170108400.0
4,4,2005-01-06,4.619286,4.636428,4.523571,4.610714,3.121253,176388800.0
5,5,2005-01-07,4.642857,4.973571,4.625000,4.946429,3.348517,556862600.0
6,6,2005-01-10,4.987857,5.050000,4.848571,4.925714,3.334495,431327400.0
7,7,2005-01-11,4.875000,4.939286,4.581429,4.611429,3.121737,652906800.0
8,8,2005-01-12,4.675000,4.707143,4.521429,4.675714,3.165255,479925600.0
9,.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
aapl_institutional_ownership

,Date Reported,Holder,pctHeld,Shares,Value,pctChange
0,2025-12-31,Vanguard Group Inc,0.0972,1426283914,356485404947,0.0192
1,2025-12-31,Blackrock Inc.,0.0786,1154665731,288597155625,0.0073
2,2025-12-31,State Street Corporation,0.0411,604056505,150977884334,0.0110
3,2025-12-31,"Geode Capital Management, LLC",0.0244,358032517,89486648173,0.0052
4,2025-12-31,"FMR, LLC",0.0209,307397264,76830872914,0.0137
5,2025-12-31,Morgan Stanley,0.0157,230483035,57606930330,0.0060
6,2025-12-31,"Berkshire Hathaway, Inc",0.0155,227917808,56965777487,-0.0432
7,2025-12-31,JPMORGAN CHASE & CO,0.0154,225419111,56341253153,-0.5237
8,2025-12-31,Price (T.Rowe) Associates Inc,0.0139,203499482,50862661027,-0.0435
9,2025-12-31,NORGES BANK,0.0131,192255086,48052236664,0.0129

In [6]:
cash_flow

,Unnamed: 0,Free Cash Flow,Repurchase Of Capital Stock,Repayment Of Debt,Issuance Of Debt,Issuance Of Capital Stock,Capital Expenditure,Interest Paid Supplemental Data,Income Tax Paid Supplemental Data,End Cash Position,...,Change In Inventory,Change In Receivables,Changes In Account Receivables,Other Non Cash Items,Stock Based Compensation,Deferred Tax,Deferred Income Tax,Depreciation Amortization Depletion,Depreciation And Amortization,Net Income From Continuing Operations
0,2025-09-30,9.876700e+10,-9.071100e+10,-1.093200e+10,4.481000e+09,NaN,-1.271500e+10,NaN,4.336900e+10,3.593400e+10,...,1.400000e+09,-7.029000e+09,-6.682000e+09,-8.900000e+07,1.286300e+10,NaN,NaN,1.169800e+10,1.169800e+10,1.120100e+11
1,2024-09-30,1.088070e+11,-9.494900e+10,-9.958000e+09,0.000000e+00,NaN,-9.447000e+09,NaN,2.610200e+10,2.994300e+10,...,-1.046000e+09,-5.144000e+09,-3.788000e+09,-2.266000e+09,1.168800e+10,NaN,NaN,1.144500e+10,1.144500e+10,9.373600e+10
2,2023-09-30,9.958400e+10,-7.755000e+10,-1.115100e+10,5.228000e+09,NaN,-1.095900e+10,3.803000e+09,1.867900e+10,3.073700e+10,...,-1.618000e+09,-4.170000e+08,-1.688000e+09,-2.227000e+09,1.083300e+10,NaN,NaN,1.151900e+10,1.151900e+10,9.699500e+10
3,2022-09-30,1.114430e+11,-8.940200e+10,-9.543000e+09,5.465000e+09,NaN,-1.070800e+10,2.865000e+09,1.957300e+10,2.497700e+10,...,1.484000e+09,-9.343000e+09,-1.823000e+09,1.006000e+09,9.038000e+09,8.950000e+08,8.950000e+08,1.110400e+10,1.110400e+10,9.980300e+10
4,2021-09-30,NaN,NaN,NaN,NaN,1.105000e+09,NaN,2.687000e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-4.774000e+09,-4.774000e+09,NaN,NaN,NaN

In [7]:
aapl_quarterly_financials

,Unnamed: 0,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,EBIT,Normalized Income,...,Other Income Expense,Other Non Operating Income Expenses,Operating Income,Operating Expense,Research And Development,Selling General And Administration,Gross Profit,Cost Of Revenue,Total Revenue,Operating Revenue
0,2025-12-31,0.0,0.175000,5.406600e+10,4.209700e+10,3.214000e+09,7.452500e+10,5.406600e+10,5.085200e+10,4.209700e+10,...,150000000.0,150000000.0,5.085200e+10,1.837900e+10,1.088700e+10,7.492000e+09,6.923100e+10,7.452500e+10,1.437560e+11,1.437560e+11
1,2025-09-30,0.0,0.162724,3.555400e+10,2.746600e+10,3.127000e+09,5.412500e+10,3.555400e+10,3.242700e+10,2.746600e+10,...,377000000.0,377000000.0,3.242700e+10,1.591400e+10,8.866000e+09,7.048000e+09,4.834100e+10,5.412500e+10,1.024660e+11,1.024660e+11
2,2025-06-30,0.0,0.164000,3.103200e+10,2.343400e+10,2.830000e+09,5.031800e+10,3.103200e+10,2.820200e+10,2.343400e+10,...,-171000000.0,-171000000.0,2.820200e+10,1.551600e+10,8.866000e+09,6.650000e+09,4.371800e+10,5.031800e+10,9.403600e+10,9.403600e+10
3,2025-03-31,0.0,0.155000,3.225000e+10,2.478000e+10,2.661000e+09,5.049200e+10,3.225000e+10,2.958900e+10,2.478000e+10,...,-279000000.0,-279000000.0,2.958900e+10,1.527800e+10,8.550000e+09,6.728000e+09,4.486700e+10,5.049200e+10,9.535900e+10,9.535900e+10
4,2024-12-31,0.0,0.147000,4.591200e+10,3.633000e+10,3.080000e+09,6.602500e+10,4.591200e+10,4.283200e+10,3.633000e+10,...,-248000000.0,-248000000.0,4.283200e+10,1.544300e+10,8.268000e+09,7.175000e+09,5.827500e+10,6.602500e+10,1.243000e+11,1.243000e+11

In [8]:
aapl_master_dataset

,Date,Open,High,Low,Close,Volume,Dividends,Splits
0,1980-12-12,0.098297,0.098725,0.098297,0.098297,469033600,0.0,0.0
1,1980-12-15,0.093597,0.093597,0.093169,0.093169,175884800,0.0,0.0
2,1980-12-16,0.086758,0.086758,0.086331,0.086331,105728000,0.0,0.0
3,1980-12-17,0.088468,0.088895,0.088468,0.088468,86441600,0.0,0.0
4,1980-12-18,0.091032,0.091460,0.091032,0.091032,73449600,0.0,0.0
...,...,...,...,...,...,...,...,...
11402,2026-03-12,258.660004,258.950012,254.179993,255.759995,40794000,0.0,0.0
11403,2026-03-13,255.479996,256.329987,249.520004,250.119995,36930000,0.0,0.0
11404,2026-03-16,252.110001,253.889999,249.880005,252.820007,32074200,0.0,0.0
11405,2026-03-17,252.960007,255.130005,252.179993,254.229996,32361600,0.0,0.0
11406,2026-03-18,252.625000,254.940002,249.000000,249.940002,34652568,0.0,0.0

In [11]:
aapl_income_statement

,Unnamed: 0,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,EBIT,Net Interest Income,...,Interest Expense Non Operating,Interest Income Non Operating,Operating Income,Operating Expense,Research And Development,Selling General And Administration,Gross Profit,Cost Of Revenue,Total Revenue,Operating Revenue
0,2025-09-30,0.0,0.156,1.447480e+11,1.120100e+11,1.169800e+10,2.209600e+11,1.447480e+11,1.330500e+11,NaN,...,NaN,NaN,1.330500e+11,6.215100e+10,3.455000e+10,2.760100e+10,1.952010e+11,2.209600e+11,4.161610e+11,4.161610e+11
1,2024-09-30,0.0,0.241,1.346610e+11,9.373600e+10,1.144500e+10,2.103520e+11,1.346610e+11,1.232160e+11,NaN,...,NaN,NaN,1.232160e+11,5.746700e+10,3.137000e+10,2.609700e+10,1.806830e+11,2.103520e+11,3.910350e+11,3.910350e+11
2,2023-09-30,0.0,0.147,1.258200e+11,9.699500e+10,1.151900e+10,2.141370e+11,1.258200e+11,1.143010e+11,-183000000.0,...,3.933000e+09,3.750000e+09,1.143010e+11,5.484700e+10,2.991500e+10,2.493200e+10,1.691480e+11,2.141370e+11,3.832850e+11,3.832850e+11
3,2022-09-30,0.0,0.162,1.305410e+11,9.980300e+10,1.110400e+10,2.235460e+11,1.305410e+11,1.194370e+11,-106000000.0,...,2.931000e+09,2.825000e+09,1.194370e+11,5.134500e+10,2.625100e+10,2.509400e+10,1.707820e+11,2.235460e+11,3.943280e+11,3.943280e+11
4,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198000000.0,...,2.645000e+09,2.843000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
for c in data:
    print(c.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11356 entries, 0 to 11355
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             11356 non-null  object
 1   Open             11356 non-null  float64
 2   High             11356 non-null  float64
 3   Low              11356 non-null  float64
 4   Close            11356 non-null  float64
 5   Volume           11356 non-null  int64
 6   Return           11356 non-null  float64
 7   Close_lag_1      11356 non-null  float64
 8   Close_lag_2      11356 non-null  float64
 9   Close_lag_3      11356 non-null  float64
 10  Return_lag_1     11356 non-null  float64
 11  Return_lag_2     11356 non-null  float64
 12  MA_7             11356 non-null  float64
 13  MA_30            11356 non-null  float64
 14  MA_50            11356 non-null  float64
 15  Volatility_7     11356 non-null  float64
 16  Volatility_30    11356 non-null  float64
 17  Volume_change    11356 non-null  float64
 18  Volume_MA_7      11356 non-null  float64
 19  High_Low_diff    11356 non-null  float64
 20  Open_Close_diff  11356 non-null  float64
 21  Target           11356 non-null  float64
 22  MA_20            11356 non-null  float64
 23  MA_ratio         11356 non-null  float64
 24  Momentum_5       11356 non-null  float64
 25  Momentum_10      11356 non-null  float64
 26  Volatility_14    11356 non-null  float64
 27  Close_to_High    11356 non-null  float64
 28  Close_to_Low     11356 non-null  float64
dtypes: float64(27), int64(1), object(1)
memory usage: 2.5+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 54 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Unnamed: 0                                      5 non-null      object
 1   Free Cash Flow                                  4 non-null      float64
 2   Repurchase Of Capital Stock                     4 non-null      float64
 3   Repayment Of Debt                               4 non-null      float64
 4   Issuance Of Debt                                4 non-null      float64
 5   Issuance Of Capital Stock                       1 non-null      float64
 6   Capital Expenditure                             4 non-null      float64
 7   Interest Paid Supplemental Data                 3 non-null      float64
 8   Income Tax Paid Supplemental Data               4 non-null      float64
 9   End Cash Position                               4 non-null      float64
 10  Beginning Cash Position                         4 non-null      float64
 11  Changes In Cash                                 4 non-null      float64
 12  Financing Cash Flow                             4 non-null      float64
 13  Cash Flow From Continuing Financing Activities  4 non-null      float64
 14  Net Other Financing Charges                     4 non-null      float64
 15  Cash Dividends Paid                             4 non-null      float64
 16  Common Stock Dividend Paid                      4 non-null      float64
 17  Net Common Stock Issuance                       4 non-null      float64
 18  Common Stock Payments                           4 non-null      float64
 19  Common Stock Issuance                           1 non-null      float64
 20  Net Issuance Payments Of Debt                   4 non-null      float64
 21  Net Short Term Debt Issuance                    4 non-null      float64
 22  Net Long Term Debt Issuance                     4 non-null      float64
 23  Long Term Debt Payments                         4 non-null      float64
 24  Long Term Debt Issuance                         4 non-null      float64
 25  Investing Cash Flow                             4 non-null      float64
 26  Cash Flow From Continuing Investing Activities  4 non-null      float64
 27  Net Other Investing Changes                     4 non-null      float64
 28  Net Investment Purchase And Sale                4 non-null      float64
 29  Sale Of Investment                              4 non-null      float64
 30  Purchase Of Investment                          4 non-null      float64
 31  Net Business Purchase And Sale                  2 non-null      float64
 32  Purchase Of Business                            2 non-null      float64
 33  Net PPE Purchase And Sale                       4 non-null      float64
 34  Purchase Of PPE                                 4 non-null      float64
 35  Operating Cash Flow                             4 non-null      float64
 36  Cash Flow From Continuing Operating Activities  4 non-null      float64
 37  Change In Working Capital                       4 non-null      float64
 38  Change In Other Working Capital                 2 non-null      float64
 39  Change In Other Current Liabilities             4 non-null      float64
 40  Change In Other Current Assets                  4 non-null      float64
 41  Change In Payables And Accrued Expense          4 non-null      float64
 42  Change In Payable                               4 non-null      float64
 43  Change In Account Payable                       4 non-null      float64
 44  Change In Inventory                             4 non-null      float64
 45  Change In Receivables                           4 non-null      float64
 46  Changes In Account Receivables                  4 non-null      float64
 47  Other Non Cash Items                            4 non-null      float64
 48  Stock Based Compensation                        4 non-null      float64
 49  Deferred Tax                                    2 non-null      float64
 50  Deferred Income Tax                             2 non-null      float64
 51  Depreciation Amortization Depletion             4 non-null      float64
 52  Depreciation And Amortization                   4 non-null      float64
 53  Net Income From Continuing Operations           4 non-null      float64
dtypes: float64(53), object(1)
memory usage: 2.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       90 non-null     object
 1   Dividends  90 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2513 entries, 0 to 2512
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        2513 non-null   object
 1   Close/Last  2513 non-null   object
 2   Volume      2513 non-null   int64
 3   Open        2513 non-null   object
 4   High        2513 non-null   object
 5   Low         2513 non-null   object
dtypes: int64(1), object(5)
memory usage: 117.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 40 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Unnamed: 0                                                  5 non-null      object
 1   Tax Effect Of Unusual Items                                 4 non-null      float64
 2   Tax Rate For Calcs                                          4 non-null      float64
 3   Normalized EBITDA                                           4 non-null      float64
 4   Net Income From Continuing Operation Net Minority Interest  4 non-null      float64
 5   Reconciled Depreciation                                     4 non-null      float64
 6   Reconciled Cost Of Revenue                                  4 non-null      float64
 7   EBITDA                                                      4 non-null      float64
 8   EBIT                                                        4 non-null      float64
 9   Net Interest Income                                         3 non-null      float64
 10  Interest Expense                                            3 non-null      float64
 11  Interest Income                                             3 non-null      float64
 12  Normalized Income                                           4 non-null      float64
 13  Net Income From Continuing And Discontinued Operation       4 non-null      float64
 14  Total Expenses                                              4 non-null      float64
 15  Total Operating Income As Reported                          4 non-null      float64
 16  Diluted Average Shares                                      4 non-null      float64
 17  Basic Average Shares                                        4 non-null      float64
 18  Diluted EPS                                                 4 non-null      float64
 19  Basic EPS                                                   4 non-null      float64
 20  Diluted NI Availto Com Stockholders                         4 non-null      float64
 21  Net Income Common Stockholders                              4 non-null      float64
 22  Net Income                                                  4 non-null      float64
 23  Net Income Including Noncontrolling Interests               4 non-null      float64
 24  Net Income Continuous Operations                            4 non-null      float64
 25  Tax Provision                                               4 non-null      float64
 26  Pretax Income                                               4 non-null      float64
 27  Other Income Expense                                        4 non-null      float64
 28  Other Non Operating Income Expenses                         4 non-null      float64
 29  Net Non Operating Interest Income Expense                   3 non-null      float64
 30  Interest Expense Non Operating                              3 non-null      float64
 31  Interest Income Non Operating                               3 non-null      float64
 32  Operating Income                                            4 non-null      float64
 33  Operating Expense                                           4 non-null      float64
 34  Research And Development                                    4 non-null      float64
 35  Selling General And Administration                          4 non-null      float64
 36  Gross Profit                                                4 non-null      float64
 37  Cost Of Revenue                                             4 non-null      float64
 38  Total Revenue                                               4 non-null      float64
 39  Operating Revenue                                           4 non-null      float64
dtypes: float64(39), object(1)
memory usage: 1.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date Reported  10 non-null     object
 1   Holder         10 non-null     object
 2   pctHeld        10 non-null     float64
 3   Shares         10 non-null     int64
 4   Value          10 non-null     int64
 5   pctChange      10 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 612.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11407 entries, 0 to 11406
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       11407 non-null  object
 1   Open       11407 non-null  float64
 2   High       11407 non-null  float64
 3   Low        11407 non-null  float64
 4   Close      11407 non-null  float64
 5   Volume     11407 non-null  int64
 6   Dividends  11407 non-null  float64
 7   Splits     11407 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 713.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 34 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Unnamed: 0                                                  5 non-null      object
 1   Tax Effect Of Unusual Items                                 5 non-null      float64
 2   Tax Rate For Calcs                                          5 non-null      float64
 3   Normalized EBITDA                                           5 non-null      float64
 4   Net Income From Continuing Operation Net Minority Interest  5 non-null      float64
 5   Reconciled Depreciation                                     5 non-null      float64
 6   Reconciled Cost Of Revenue                                  5 non-null      float64
 7   EBITDA                                                      5 non-null      float64
 8   EBIT                                                        5 non-null      float64
 9   Normalized Income                                           5 non-null      float64
 10  Net Income From Continuing And Discontinued Operation       5 non-null      float64
 11  Total Expenses                                              5 non-null      float64
 12  Total Operating Income As Reported                          5 non-null      float64
 13  Diluted Average Shares                                      5 non-null      float64
 14  Basic Average Shares                                        5 non-null      float64
 15  Diluted EPS                                                 5 non-null      float64
 16  Basic EPS                                                   5 non-null      float64
 17  Diluted NI Availto Com Stockholders                         5 non-null      float64
 18  Net Income Common Stockholders                              5 non-null      float64
 19  Net Income                                                  5 non-null      float64
 20  Net Income Including Noncontrolling Interests               5 non-null      float64
 21  Net Income Continuous Operations                            5 non-null      float64
 22  Tax Provision                                               5 non-null      float64
 23  Pretax Income                                               5 non-null      float64
 24  Other Income Expense                                        5 non-null      float64
 25  Other Non Operating Income Expenses                         5 non-null      float64
 26  Operating Income                                            5 non-null      float64
 27  Operating Expense                                           5 non-null      float64
 28  Research And Development                                    5 non-null      float64
 29  Selling General And Administration                          5 non-null      float64
 30  Gross Profit                                                5 non-null      float64
 31  Cost Of Revenue                                             5 non-null      float64
 32  Total Revenue                                               5 non-null      float64
 33  Operating Revenue                                           5 non-null      float64
dtypes: float64(33), object(1)
memory usage: 1.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  14 non-null     object
 1   Date        9 non-null      object
 2   Open        9 non-null      float64
 3   High        9 non-null      float64
 4   Low         9 non-null      float64
 5   Close       9 non-null      float64
 6   Adj Close   9 non-null      float64
 7   Volume      9 non-null      float64
dtypes: float64(6), object(2)
memory usage: 1.0+ KB
None